# Generated by Django 2.0.1 on 2018-02-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.AddField(
            model_name='purchase',
            name='username',
            field=models.CharField(default='AnonymousUser', max_length=150, unique=True),
        ),
    ]
