# Generated by Django 2.0.1 on 2018-02-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20180201_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
