# Generated by Django 2.0.1 on 2018-02-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20180201_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='game',
        ),
        migrations.AddField(
            model_name='purchase',
            name='gameid',
            field=models.IntegerField(default=1),
        ),
    ]
