# Generated by Django 2.0.1 on 2018-02-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
