# Generated by Django 2.0.1 on 2018-02-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180123_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='developer',
            field=models.BooleanField(),
        ),
    ]
