# Generated by Django 2.0.1 on 2018-02-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180201_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='developer',
            field=models.BooleanField(default=False),
        ),
    ]
