# Generated by Django 2.0.1 on 2018-02-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20180201_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='one_time_service',
        ),
        migrations.AddField(
            model_name='profile',
            name='developer',
            field=models.BooleanField(default=False),
        ),
    ]
