# Generated by Django 2.0.1 on 2018-02-09 12:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamelist', '0006_auto_20180206_1154'),
        ('authentication', '0007_auto_20180201_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameState', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('highscore', models.FloatField(null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamedata', to='gamelist.Game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamedata', to='authentication.Profile')),
            ],
        ),
    ]
