# Generated by Django 2.0.1 on 2018-02-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0002_auto_20180211_0149'),
        ('gamepage', '0002_auto_20180212_2103'),
    ]

    operations = [
    ]
