# Generated by Django 2.0.1 on 2018-02-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20180201_0927'),
        ('gamelist', '0004_auto_20180206_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owners',
            field=models.ManyToManyField(null=True, related_name='purchasedgames', to='authentication.Profile'),
        ),
    ]
