# Generated by Django 2.0.1 on 2018-02-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0013_auto_20180212_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, default='http://www.publicdomainpictures.net/pictures/40000/velka/question-mark.jpg'),
        ),
    ]
