# Generated by Django 2.0.1 on 2018-02-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0014_auto_20180213_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
