# Generated by Django 2.0.1 on 2018-02-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0015_auto_20180213_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('ACTION', 'Action'), ('ARCADE', 'Arcade'), ('PUZZLE', 'Puzzle'), ('RACING', 'Racing'), ('SHOOTER', 'Shooter'), ('STRATEGY', 'Strategy')], default=None, max_length=25),
        ),
    ]
