# Generated by Django 2.0.1 on 2018-02-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0008_auto_20180216_1658'),
        ('gamelist', '0016_game_category'),
    ]

    operations = [
    ]
